# Render configuration for AI Career Mentor (backend + frontend)
# Two web services: FastAPI backend + Streamlit frontend

services:
  - type: web
    name: ai-career-mentor-backend
    env: python
    branch: main
    pythonVersion: 3.12.10
    buildCommand: pip install -r requirements_render.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 7311
    plan: free
    healthCheckPath: /
    envVars:
      - key: LLM_API_KEY
        sync: false
      - key: JOB_API_KEY
        sync: false
      - key: MODEL_NAME
        value: "gemini-pro"
      - key: VECTOR_DB_PATH
        value: "./data/skills_index.faiss"
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: ai-career-mentor-ui
    env: python
    branch: main
    pythonVersion: 3.12.10
    buildCommand: pip install -r requirements_render.txt
    startCommand: streamlit run ui/app.py --server.port=7312 --server.address=0.0.0.0
    plan: free
    envVars:
      - key: BACKEND_URL
        sync: false
