services:
  - type: web
    name: ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 7311
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: HF_HOME
        value: /opt/render/.cache/huggingface
      - key: TRANSFORMERS_CACHE
        value: /opt/render/.cache/transformers
    plan: free

  - type: web
    name: ai-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui/app.py --server.port=7312 --server.address=0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://ai-backend.onrender.com
    plan: free
