# Render configuration for ai-career-mentor (backend + frontend)
# This file declares two web services that can be used by Render's Git-based deploy.

services:
  - type: web
    name: ai-career-mentor-backend
    env: python
    branch: main
    buildCommand: pip install -r requirements_render.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /
    envVars:
      - key: LLM_API_KEY
        value: ""
        required: true
      - key: JOB_API_KEY
        value: ""
        required: false
      - key: MODEL_NAME
        value: "chat-bison-001"
        required: false
      - key: VECTOR_DB_PATH
        value: "./data/skills_index.faiss"
        required: false
      - key: FRONTEND_URL
        value: ""
        required: false

  - type: web
    name: ai-career-mentor-ui
    env: python
    branch: main
    buildCommand: pip install -r requirements_render.txt
    startCommand: streamlit run ui/app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: ""
        required: true

# Notes:
# - After the backend deploys, paste its public URL into the frontend BACKEND_URL value
#   in Render's dashboard or via the Render UI for this service's environment variables.
# - Both services use the lightweight `requirements_render.txt` to reduce memory/build footprint.